# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'prayerUI.ui'
#
# Created by: PyQt5 UI code generator 5.10.1
#
# WARNING! All changes made in this file will be lost!

from PyQt5 import QtCore, QtGui, QtWidgets

class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(605, 312)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(MainWindow.sizePolicy().hasHeightForWidth())
        MainWindow.setSizePolicy(sizePolicy)
        MainWindow.setMinimumSize(QtCore.QSize(605, 312))
        MainWindow.setMaximumSize(QtCore.QSize(605, 312))
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.gridLayout_2 = QtWidgets.QGridLayout(self.centralwidget)
        self.gridLayout_2.setObjectName("gridLayout_2")
        self.gridLayout = QtWidgets.QGridLayout()
        self.gridLayout.setHorizontalSpacing(3)
        self.gridLayout.setObjectName("gridLayout")
        self.newNamesButton = QtWidgets.QPushButton(self.centralwidget)
        self.newNamesButton.setObjectName("newNamesButton")
        self.gridLayout.addWidget(self.newNamesButton, 4, 0, 1, 2)
        self.name2Button = QtWidgets.QPushButton(self.centralwidget)
        self.name2Button.setObjectName("name2Button")
        self.gridLayout.addWidget(self.name2Button, 1, 1, 1, 1)
        self.name3Label = QtWidgets.QLabel(self.centralwidget)
        font = QtGui.QFont()
        font.setPointSize(16)
        self.name3Label.setFont(font)
        self.name3Label.setText("")
        self.name3Label.setAlignment(QtCore.Qt.AlignCenter)
        self.name3Label.setObjectName("name3Label")
        self.gridLayout.addWidget(self.name3Label, 2, 0, 1, 1)
        self.name2Label = QtWidgets.QLabel(self.centralwidget)
        font = QtGui.QFont()
        font.setPointSize(16)
        self.name2Label.setFont(font)
        self.name2Label.setText("")
        self.name2Label.setAlignment(QtCore.Qt.AlignCenter)
        self.name2Label.setObjectName("name2Label")
        self.gridLayout.addWidget(self.name2Label, 1, 0, 1, 1)
        self.name1Label = QtWidgets.QLabel(self.centralwidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.MinimumExpanding, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.name1Label.sizePolicy().hasHeightForWidth())
        self.name1Label.setSizePolicy(sizePolicy)
        self.name1Label.setMinimumSize(QtCore.QSize(460, 0))
        font = QtGui.QFont()
        font.setFamily("MS Shell Dlg 2")
        font.setPointSize(16)
        self.name1Label.setFont(font)
        self.name1Label.setText("")
        self.name1Label.setAlignment(QtCore.Qt.AlignCenter)
        self.name1Label.setObjectName("name1Label")
        self.gridLayout.addWidget(self.name1Label, 0, 0, 1, 1)
        self.name1Button = QtWidgets.QPushButton(self.centralwidget)
        self.name1Button.setObjectName("name1Button")
        self.gridLayout.addWidget(self.name1Button, 0, 1, 1, 1)
        self.name3Button = QtWidgets.QPushButton(self.centralwidget)
        self.name3Button.setObjectName("name3Button")
        self.gridLayout.addWidget(self.name3Button, 2, 1, 1, 1)
        self.prayedForAllButton = QtWidgets.QPushButton(self.centralwidget)
        self.prayedForAllButton.setObjectName("prayedForAllButton")
        self.gridLayout.addWidget(self.prayedForAllButton, 3, 1, 1, 1)
        self.gridLayout_2.addLayout(self.gridLayout, 1, 0, 1, 1)
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 605, 31))
        self.menubar.setObjectName("menubar")
        self.menuFile = QtWidgets.QMenu(self.menubar)
        self.menuFile.setObjectName("menuFile")
        self.menuEdit = QtWidgets.QMenu(self.menubar)
        self.menuEdit.setObjectName("menuEdit")
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)
        self.actionImport = QtWidgets.QAction(MainWindow)
        self.actionImport.setObjectName("actionImport")
        self.actionExport = QtWidgets.QAction(MainWindow)
        self.actionExport.setObjectName("actionExport")
        self.actionAdd_new_name = QtWidgets.QAction(MainWindow)
        self.actionAdd_new_name.setObjectName("actionAdd_new_name")
        self.actionEdit_names = QtWidgets.QAction(MainWindow)
        self.actionEdit_names.setObjectName("actionEdit_names")
        self.actionQuit = QtWidgets.QAction(MainWindow)
        self.actionQuit.setObjectName("actionQuit")
        self.actionReset_names = QtWidgets.QAction(MainWindow)
        self.actionReset_names.setObjectName("actionReset_names")
        self.menuFile.addAction(self.actionImport)
        self.menuFile.addAction(self.actionExport)
        self.menuFile.addAction(self.actionReset_names)
        self.menuFile.addAction(self.actionQuit)
        self.menuEdit.addAction(self.actionAdd_new_name)
        self.menuEdit.addAction(self.actionEdit_names)
        self.menubar.addAction(self.menuFile.menuAction())
        self.menubar.addAction(self.menuEdit.menuAction())

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "Prayer App"))
        self.newNamesButton.setText(_translate("MainWindow", "Get new names"))
        self.name2Button.setText(_translate("MainWindow", "Prayed for 2"))
        self.name1Button.setText(_translate("MainWindow", "Prayed for 1"))
        self.name3Button.setText(_translate("MainWindow", "Prayer for 3"))
        self.prayedForAllButton.setText(_translate("MainWindow", "Prayed for all "))
        self.menuFile.setTitle(_translate("MainWindow", "File"))
        self.menuEdit.setTitle(_translate("MainWindow", "Edit"))
        self.actionImport.setText(_translate("MainWindow", "Import"))
        self.actionExport.setText(_translate("MainWindow", "Export"))
        self.actionAdd_new_name.setText(_translate("MainWindow", "Add new name"))
        self.actionEdit_names.setText(_translate("MainWindow", "Edit names"))
        self.actionQuit.setText(_translate("MainWindow", "Quit"))
        self.actionReset_names.setText(_translate("MainWindow", "Reset names"))

